name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=19
  - numpy=1.17
  - scipy=1.3.1
  - pytorch=1.2.0
  - torchvision=0.4
  # MacOS Binaries dont support CUDA, install from source if CUDA is needed
  # - cudatoolkit=10.0
  # MacOS dont support gpu with tensorflow.
  # - tensorflow-gpu=1.14
  - tensorflow=1.14
  - tensorboard=1.14
  - scikit-learn=0.21.3
  - matplotlib=3.1
  - pillow=6.1
  - fastdtw=0.3
  - numba=0.45.1
  - tqdm=4.35.0
  - jupyter
  - nb_conda
  - nb_conda_kernels
  - pip:
    - tensorboardx
    - torchsummary

